[env]
QEMU = "qemu-system-riscv64"
KERNEL = "kernel/target/riscv64gc-unknown-none-elf/release/kernel"
USER = "user/target/riscv64gc-unknown-none-elf/release/user"

[tasks.run]
script = ['''
#!/bin/bash
set -xue

(cd user && cargo build --release)

cp $USER kernel/shell

(cd kernel && cargo build --release)

$QEMU -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
  -d guest_errors \
  -kernel $KERNEL
''']

[tasks.objdump]
script = ['''
llvm-objdump -d $KERNEL
''']

[tasks.clean]
script = ['''
(cd kernel && cargo clean)
(cd user && cargo clean)
rm -f kernel/shell.bin kernel/shell.bin.o
''']

[tasks.fmt]
script = ['''
(cd kernel && cargo fmt)
(cd user && cargo fmt)
''']

[tasks.test]
script = ['''
(cd kernel && cargo build --tests)
TEST_TARGET=$(find kernel/target/riscv64gc-unknown-none-elf/debug/deps -type f ! \( -name "*.d" -o -name "*.rmeta" \) | head -n 1)

$QEMU -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
  -d guest_errors \
  -kernel $TEST_TARGET
''']

[config]
skip_core_tasks = true
