[tasks.run]
script = ['''
#!/bin/bash
set -xue

QEMU=qemu-system-riscv64
KERNEL=kernel/target/riscv64gc-unknown-none-elf/release/kernel
USER=user/target/riscv64gc-unknown-none-elf/release/user

(cd user && cargo build --release)

cp $USER kernel/shell
llvm-objcopy -O binary kernel/shell  kernel/shell.bin

(cd kernel && cargo build --release)

$QEMU -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
  -d guest_errors \
  -kernel $KERNEL
''']

[tasks.objdump]
script = ['''
llvm-objdump -d kernel/target/riscv64gc-unknown-none-elf/release/kernel
''']

[tasks.clean]
script = ['''
(cd kernel && cargo clean)
(cd user && cargo clean)
rm -f kernel/shell.bin kernel/shell.bin.o
''']

[tasks.fmt]
script = ['''
(cd kernel && cargo fmt)
(cd user && cargo fmt)
''']

[config]
skip_core_tasks = true
